---
- name: Configure NAT instance
  hosts: jenkins_aws_nat_instance
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/jenkins-poc-key.pem"
  pre_tasks:
    - name: Wait for SSH to become available over SSM
      ansible.builtin.wait_for_connection:
        timeout: 180
        sleep: 10
  roles:
    - nat

- name: Configure Jenkins Controller
  hosts: jenkins_aws_controller_instance
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/jenkins-poc-key.pem"
  pre_tasks:
    - name: Wait for SSH to become available over SSM
      ansible.builtin.wait_for_connection:
        timeout: 180
        sleep: 10
  roles:
    - jenkins_controller